<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit04e0ce1e8661860c929b98c5800a412e
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'MessageBird\\' => 12,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'MessageBird\\' => 
        array (
            0 => __DIR__ . '/..' . '/messagebird/php-rest-api/src/MessageBird',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit04e0ce1e8661860c929b98c5800a412e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit04e0ce1e8661860c929b98c5800a412e::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
